export const textFieldStyle = {
  color: "#3c4852",
  width: "100%",
  marginTop: "1rem",
};
export const inputFields = [
  // {
  //   id: 1,
  //   name: "fist_name",
  //   label: "First Name",
  //   type: "text",
  //   placeholder: "First Name",
  //   inputProps: {
  //     maxLength: 50,
  //   },
  //   sx: textFieldStyle,
  //   required: true,
  //   error: false,
  //   helperText: "",
  // },
  {
    id: 1,
    name: "full_name",
    label: "Full Name",
    type: "text",
    placeholder: "Full Name",
    inputProps: {
      maxLength: 50,
    },
    sx: { ...textFieldStyle, gridColumn: "1/3" },
    required: true,
    error: false,
    helperText: "",
  },
  {
    id: 3,
    name: "email",
    label: "Email",
    type: "email",
    placeholder: "E-mail Address",
    inputProps: {
      maxLength: 50,
    },
    sx: { ...textFieldStyle, gridColumn: "1/3" },
    required: true,
    error: false,
    helperText: "",
  },
  {
    id: 4,
    name: "phone",
    label: "Phone Number",
    type: "text",
    placeholder: "Phone Number",
    inputProps: { maxLength: 20 },
    required: true,
    error: false,
    helperText: "",
  },
  {
    id: 5,
    name: "state",
    label: "State",
    type: "text",
    placeholder: "State of residence",
    inputProps: {
      maxLength: 520,
    },
    sx: { ...textFieldStyle, gridColumn: "1/3" },
    required: true,
    error: false,
    helperText: "",
  },
];
